### ISSUE TITLE
Lots of Weirdness

### ISSUE THREAD

**Issue by Chickensaver** [RoadrunnerWMC/Newer-Credits-Editor#2]
![credits editor not working](https://user-images.githubusercontent.com/27451052/27508680-7a41e19a-58b8-11e7-8f8c-2c6ea9d8f3f7.PNG)
I have tried my best to find out what is wrong, but honestly, I can't do much seeing as I barely understand python and I run a windows computer with python, etc. downloaded onto it.  I had no idea what was wrong so I decided to run winbuild.py instead.  Interestingly, it will not run unless I open it and delete the beginning comments with ######### signs.  Once I do run it, it creates a distrib folder.  Previously, it said I didn't have the credits editor py file in the distrib folder, so I put it in there, ran it again, and boom.  Distrib overwrites itself and the credits editor py file is gone.  That doesn't matter, because I just redownloaded the entire thing, but I have no idea what I am supposed to do.  All in all, this really isn't urgent because I don't actually NEED to edit the credits as of now but it would be nice to have a fix within the next six months 😃 

P.S. If this is way too much information/not enough information, please let me know.

**Comment by RoadrunnerWMC** [comment]
An update to NCE about a month ago bumped the minimum required Python version up to 3.6. (I forgot to mention this in the readme at the time; I updated it now to fix that. Sorry.)

Your screenshot shows that you're using Python 3.4; update to 3.6 and it should work. (You'll probably need to install PyQt again for the new copy of Python, as well.)

**Comment by Chickensaver** [comment]
Thank you so much!  I will also assume that Python 3.6 will work for the other programs unless you tell me otherwise.
